const mongoose= require('mongoose');

const IncidenciaSchema = mongoose.Schema({

    alumne: String,
    grupo: String,
    profesor: String,
    horario: String,
    data: Date,
    hora: String,
    lloc: String,
    check: String,
    opcionA: String,
    opcionB: String,
    opcionC: String,
    opcionD: String,
    opcionE: String,
    opcionF: String,
    dias: String,
    tareas: String,
    diastarea: String,
    horatarea: String,
    iniciodias: String,
    findias: String,
    diassuspenso: String,
    iniciodiassuspenso: String,
    findiassuspenso: String,
    leveA: String,
    leveB: String,
    leveC: String,
    leveD: String,
    leveE: String,
    leveF: String,
    leveG: String,
    leveH: String,
    leveI: String,
    leveJ: String,
    leveK: String,
    leveL: String,
    leveM: String,
    leveN: String,
    leveO: String,
    leveP: String,
    leveQ: String,
    leveR: String,
    leveS: String,
    graveA: String,
    graveB: String,
    graveC: String,
    graveD: String,
    graveE: String,
    graveF: String,
    graveG: String,
    graveH: String,
    graveI: String,
    graveJ: String,
    graveK: String,
    graveL: String,
    graveM: String,
    graveN: String,
    graveO: String,
    graveP: String,
    telefono: String,
    correo: String,
    alumno: String,
    padre: String,
    diafirma: String,
    mesfirma: String,
    yearfirma: String,
    firmadirector: String,
},{
    timestamps:true
});


module.exports = mongoose.model('Incidencia',IncidenciaSchema);